$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$temp=Join-Path ([IO.Path]::GetTempPath()) ('puntash v22 win dashboard '+[guid]::NewGuid().ToString('N'))
function Assert([bool]$ok,[string]$name){if(-not$ok){throw "V22_WIN_DASHBOARD_FAIL=$name"};Write-Host "V22_WIN_DASHBOARD_PASS=$name"}
$proc=$null
try{
  $project=Join-Path $temp 'project';$install=Join-Path $project '.comprehensive-qa';New-Item -ItemType Directory $project -Force|Out-Null;Copy-Item (Join-Path $root 'runtime') $install -Recurse -Force
  $state=Join-Path $install 'state';$evidence=Join-Path $install 'evidence';$reports=Join-Path $install 'reports\dashboard';New-Item -ItemType Directory $state,$evidence,$reports,(Join-Path $project 'docs') -Force|Out-Null
  Copy-Item (Join-Path $root 'TERMS_VERSION') (Join-Path $install 'TERMS_VERSION') -Force;Copy-Item (Join-Path $root 'LEGAL_MANIFEST.json') (Join-Path $install 'LEGAL_MANIFEST.json') -Force
  $legal=(Get-Content (Join-Path $root 'LEGAL_MANIFEST.json') -Raw|ConvertFrom-Json).documents;foreach($x in $legal.PSObject.Properties){Copy-Item (Join-Path $root $x.Name) (Join-Path $install $x.Name) -Force}
  [ordered]@{version='2.2.0';previous_version='2.1.0'}|ConvertTo-Json|Set-Content (Join-Path $install 'INSTALLATION.json') -Encoding UTF8
  [ordered]@{terms_version=(Get-Content (Join-Path $root 'TERMS_VERSION') -Raw).Trim();accepted_by_human_attestation=$true;legal_document_sha256=$legal}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $state 'HUMAN_ACCEPTANCE_RECEIPT.json') -Encoding UTF8
  # Human-approved baseline policy.
  $policyTool=Join-Path $install 'tools\policy-manager.ps1';$p=(& $policyTool -Operation Get|Out-String)|ConvertFrom-Json;$candidate=Join-Path $temp 'candidate.json';$p.permissions.preset='REPORT_ONLY';$p|ConvertTo-Json -Depth 20|Set-Content $candidate -Encoding UTF8;& $policyTool -Operation Apply -PolicyJsonPath $candidate -OwnerApproved -ApprovalSource manual_cli|Out-Null
  $probe=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);$probe.Start();$port=([Net.IPEndPoint]$probe.LocalEndpoint).Port;$probe.Stop();$token='v22-windows-token';$out=Join-Path $temp 'server.out';$err=Join-Path $temp 'server.err';$server=Join-Path $install 'tools\dashboard-control.ps1'
  $psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=(Get-Command pwsh).Source;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;foreach($a in @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$server,'-ProjectPath',$project,'-Port',[string]$port,'-IdleMinutes','5','-NoBrowser','-ControlToken',$token)){[void]$psi.ArgumentList.Add($a)};$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$proc=[Diagnostics.Process]::Start($psi)
  $base="http://127.0.0.1:$port/";$ready=$false;foreach($i in 1..60){Start-Sleep -Milliseconds 200;try{$x=Invoke-WebRequest -Uri $base -UseBasicParsing -TimeoutSec 1;if($x.StatusCode-eq200){$ready=$true;break}}catch{}};Assert $ready 'server_ready'
  $headers=@{'X-QA-Control-Token'=$token}
  try{Invoke-RestMethod -Uri ($base+'api/overview') -TimeoutSec 2|Out-Null;throw 'unauth allowed'}catch{Assert ($_.Exception.Response.StatusCode.value__-eq403) 'unauthorized_overview_denied'}
  try{Invoke-RestMethod -Uri ($base+'api/overview') -Headers @{'X-QA-Control-Token'=$token;Origin='http://evil.example'} -TimeoutSec 2|Out-Null;throw 'foreign origin allowed'}catch{Assert ($_.Exception.Response.StatusCode.value__-eq403) 'foreign_origin_token_reuse_denied'}
  $overview=Invoke-RestMethod -Uri ($base+'api/overview') -Headers $headers -TimeoutSec 5;Assert ($overview.ok-eq$true -and $overview.overview.diagnostics.acceptance.valid-eq$true) 'overview_acceptance_projection'
  try{Invoke-RestMethod -Uri ($base+'api/scan-now') -Method Post -Headers $headers -ContentType 'application/json' -Body '{}' -TimeoutSec 5|Out-Null;throw 'scan should require setup'}catch{Assert ($_.Exception.Response.StatusCode.value__-eq409) 'scan_requires_runner'}
  Set-Content (Join-Path $evidence 'proof.txt') 'proof-data' -Encoding UTF8
  $ev=Invoke-WebRequest -Uri ($base+'api/evidence?path=evidence%2Fproof.txt') -Headers $headers -UseBasicParsing -TimeoutSec 5;Assert ($ev.Content -match 'proof-data') 'evidence_safe_read'
  try{Invoke-WebRequest -Uri ($base+'api/evidence?path=..%2Fstate%2FOWNER_POLICY.json') -Headers $headers -UseBasicParsing -TimeoutSec 5|Out-Null;throw 'traversal allowed'}catch{Assert ($_.Exception.Response.StatusCode.value__-eq404) 'evidence_traversal_denied'}
  # Configure native manual runner with argument spaces/quotes.
  $policy=(Invoke-RestMethod -Uri ($base+'api/policy') -Headers $headers -TimeoutSec 5).policy;$helper=Join-Path $project 'manual helper.ps1';Set-Content $helper 'Start-Sleep -Milliseconds 1200; Write-Output "manual-native-ok"' -Encoding UTF8;$policy.permissions.preset='SAFE_FIXES';$policy.schedule.enabled=$false;$policy.schedule.executor_mode='LOCAL_COMMAND';$policy.schedule.executor.command=(Get-Command pwsh).Source;$policy.schedule.executor.arguments=@('-NoProfile','-NonInteractive','-File',$helper);$body=$policy|ConvertTo-Json -Depth 30;$saved=Invoke-RestMethod -Uri ($base+'api/policy') -Method Post -Headers $headers -ContentType 'application/json' -Body $body -TimeoutSec 20;Assert ($saved.ok-eq$true) 'policy_control_configures_runner'
  $started=Invoke-RestMethod -Uri ($base+'api/scan-now') -Method Post -Headers $headers -ContentType 'application/json' -Body '{}' -TimeoutSec 5;Assert ($started.started-eq$true) 'scan_now_started'
  Start-Sleep -Milliseconds 350;$st=Invoke-RestMethod -Uri ($base+'api/scan-status') -Headers $headers -TimeoutSec 5;Assert ($st.active-eq$true -and [string]$st.scan.last_result-in@('STARTING','RUNNING')) 'scan_live_status'
  foreach($i in 1..60){Start-Sleep -Milliseconds 200;$st=Invoke-RestMethod -Uri ($base+'api/scan-status') -Headers $headers -TimeoutSec 5;if($st.scan.last_result-eq'SUCCESS'){break}};Assert ($st.scan.last_result-eq'SUCCESS') 'scan_success'
  # Approval exact ALLOW.
  $current=(Invoke-RestMethod -Uri ($base+'api/policy') -Headers $headers -TimeoutSec 5).policy;$request=[ordered]@{request_id='REQ-WIN-V22-1';created_at=(Get-Date).ToString('o');policy_revision=$current.policy_revision;finding_id='F-WIN-V22';risk='LOW';category='documentation';change_summary='Update safe documentation';evidence_refs=@('evidence/proof.txt');target_paths=@('docs/approved.md');expected_behavior_proven=$true;reversible=$true};($request|ConvertTo-Json -Compress)|Add-Content (Join-Path $state 'APPROVAL_REQUESTS.jsonl') -Encoding UTF8
  $q=Invoke-RestMethod -Uri ($base+'api/approvals') -Headers $headers -TimeoutSec 5;$qi=@($q.approvals|Where-Object{$_.request_id-eq'REQ-WIN-V22-1'}|Select-Object -First 1);Assert ($qi.Count-eq1 -and -not[string]::IsNullOrWhiteSpace([string]$qi[0].request_hash)) 'approval_queue_visible'
  $decisionBody=[ordered]@{request_id='REQ-WIN-V22-1';request_hash=[string]$qi[0].request_hash;decision='APPROVE'}|ConvertTo-Json -Compress;$decision=Invoke-RestMethod -Uri ($base+'api/approval') -Method Post -Headers $headers -ContentType 'application/json' -Body $decisionBody -TimeoutSec 20;Assert ($decision.ok-eq$true -and -not[string]::IsNullOrWhiteSpace([string]$decision.decision.authorization_id)) 'approval_uses_native_canonical_authorizer'
  # Corrupt policy -> recovery.
  Set-Content (Join-Path $state 'OWNER_POLICY.json') '{bad-json' -Encoding UTF8;$dg=Invoke-RestMethod -Uri ($base+'api/diagnostics') -Headers $headers -TimeoutSec 5;Assert (@($dg.diagnostics.issues|Where-Object{$_.code-eq'POLICY_INVALID'}).Count-eq1) 'recovery_detects_invalid_policy'
  $rec=Invoke-RestMethod -Uri ($base+'api/recovery') -Method Post -Headers $headers -ContentType 'application/json' -Body '{"action":"reset_policy_to_observe_only"}' -TimeoutSec 20;Assert ($rec.ok-eq$true -and $rec.policy.permissions.preset-eq'REPORT_ONLY' -and $rec.policy.schedule.enabled-eq$false) 'recovery_safe_reset'
  try{Invoke-RestMethod -Uri ($base+'api/scheduler-action') -Method Post -Headers $headers -ContentType 'application/json' -Body '{"action":"shell"}' -TimeoutSec 5|Out-Null;throw 'bad scheduler action allowed'}catch{Assert ($_.Exception.Response.StatusCode.value__-eq400) 'scheduler_action_allowlist'}
  Invoke-RestMethod -Uri ($base+'api/shutdown') -Method Post -Headers $headers -ContentType 'application/json' -Body '{}' -TimeoutSec 5|Out-Null;$proc.WaitForExit(10000)|Out-Null;Assert $proc.HasExited 'clean_shutdown'
  Write-Host 'V22_WIN_DASHBOARD_RESULT=PASS'
}finally{if($proc-and-not$proc.HasExited){try{$proc.Kill($true)}catch{}};if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
exit 0
